version: '3'

services:
  mysql.monolito:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: caelum123
      MYSQL_DATABASE: cibus
    volumes:
      - mysql.cibus:/var/lib/mysql
volumes:
  mysql.cibus:
